# Generated by Django 5.2 on 2026-09-27 23:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoSolicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Estudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('metodo_tecnica', models.CharField(blank=True, max_length=100, null=True)),
                ('unidad_medida', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Extraccionista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('legajo', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('matricula', models.CharField(max_length=50, unique=True)),
                ('especialidad', models.CharField(max_length=100)),
                ('validado_colegio', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('dni', models.CharField(max_length=15, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('domicilio', models.CharField(blank=True, max_length=200, null=True)),
                ('cap', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Recepcionista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ResponsableAnalisis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('legajo', models.CharField(max_length=50, unique=True)),
                ('cargo', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='RangoReferencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_min', models.FloatField()),
                ('valor_max', models.FloatField()),
                ('genero', models.CharField(blank=True, max_length=20, null=True)),
                ('edad_min', models.IntegerField(default=0)),
                ('edad_max', models.IntegerField(default=120)),
                ('estudio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analisis_bioquimico.estudio')),
            ],
        ),
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_emision', models.DateField()),
                ('archivo_pdf', models.FileField(blank=True, null=True, upload_to='recetas/')),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analisis_bioquimico.medico')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analisis_bioquimico.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='SolicitudAnalisis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='analisis_bioquimico.estadosolicitud')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analisis_bioquimico.paciente')),
                ('recepcionista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analisis_bioquimico.recepcionista')),
                ('receta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='analisis_bioquimico.receta')),
            ],
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50)),
                ('estado', models.CharField(max_length=50)),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analisis_bioquimico.solicitudanalisis')),
            ],
        ),
        migrations.CreateModel(
            name='Muestra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50)),
                ('fecha_hora_extraccion', models.DateTimeField(auto_now_add=True)),
                ('extraccionista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analisis_bioquimico.extraccionista')),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analisis_bioquimico.solicitudanalisis')),
            ],
        ),
        migrations.CreateModel(
            name='Comprobante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_emision', models.DateTimeField(auto_now_add=True)),
                ('cap', models.CharField(blank=True, max_length=50, null=True)),
                ('numero_paciente', models.IntegerField()),
                ('muestra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analisis_bioquimico.muestra')),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analisis_bioquimico.solicitudanalisis')),
            ],
        ),
        migrations.CreateModel(
            name='SolicitudEstudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(default='Pendiente', max_length=50)),
                ('estudio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analisis_bioquimico.estudio')),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analisis_bioquimico.solicitudanalisis')),
            ],
        ),
        migrations.CreateModel(
            name='Resultado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_hallado', models.FloatField()),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analisis_bioquimico.responsableanalisis')),
                ('solicitud_estudio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analisis_bioquimico.solicitudestudio')),
            ],
        ),
    ]
